DELETE http://localhost:3003/api/blogs/6a01d224d27610b3c9723732
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3R1c2VyIiwiaWQiOiI2OWZkZDU4MjZlOTliMTVhYzEyOWM4NzYiLCJpYXQiOjE3NzgzMTY5NTV9.bPfU6KQm8fSj1zR33l0SAcmdAne7FZrIjVp-xI5JQ14